Simple_Profiler/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root 'profiles#user_page'
    get 'main/list_of_users', to: 'main#list_of_users', as: 'accounts'
    get 'main/:id/admin', to: 'main#admin', as: 'make_admin'
    get 'main/:id/approved', to: 'main#approved', as: 'approved'
    resources :profiles, :only => [:index, :show, :edit, :new]
      patch 'profiles/:id/edit', to: 'profiles#update'
      post 'profiles/new', to: 'profiles#create'
    resources :trainings, :only => [:index, :show, :edit, :destroy, :new]
      patch 'trainings/:id/edit', to: 'trainings#update'
      post 'trainings/new', to: 'trainings#create'
    resources :accomplishments, :only => [:index, :show, :edit, :destroy, :new]
      patch 'accomplishments/:id/edit', to: 'accomplishments#update'
      post 'accomplishments/new', to: 'accomplishments#create'
  end
  root 'main#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Simple_Profiler/app/views/layouts/_hamburger.html.erb
<button type="button" class="hamburger is-closed" data-toggle="offcanvas">
  <span class="hamb-top"></span>
  <span class="hamb-middle"></span>
  <span class="hamb-bottom"></span>
</button>

Simple_Profiler/app/views/layouts/_header.html.erb
<div class="overlay"></div>
<nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
  <ul class="nav sidebar-nav">
    <li class="sidebar-brand">
      <a href="#">
        Simple Profiler
      </a>
    </li>
    <li><%= link_to 'Home', root_path %></li>
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <li><%= link_to 'List of Accounts', accounts_path %></li>
      <% end %>
      <li>
        <%= link_to 'Settings', edit_user_registration_path %>
      </li>
      <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to 'Log in', new_user_session_path %></li>
      <li><%= link_to 'Create new Account', new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>

Simple_Profiler/app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

Simple_Profiler/app/views/layouts/_scripts.html.erb
<script>
    $(document).ready(function () {
        var trigger = $('.hamburger'),
            overlay = $('.overlay'),
            isClosed = false;

        trigger.click(function () {
            hamburger_cross();
        });

        function hamburger_cross() {

            if (isClosed == true) {
                overlay.hide();
                trigger.removeClass('is-open');
                trigger.addClass('is-closed');
                isClosed = false;
            } else {
                overlay.show();
                trigger.removeClass('is-closed');
                trigger.addClass('is-open');
                isClosed = true;
            }
        }

        $('[data-toggle="offcanvas"]').click(function () {
            $('#wrapper').toggleClass('toggled');
        });
    });

    $(function () {
        $('.button-checkbox').each(function () {
            var $widget = $(this),
                $button = $widget.find('button'),
                $checkbox = $widget.find('input:checkbox'),
                color = $button.data('color'),
                settings = {
                    on: {
                        icon: 'glyphicon glyphicon-check'
                    },
                    off: {
                        icon: 'glyphicon glyphicon-unchecked'
                    }
                };

            $button.on('click', function () {
                $checkbox.prop('checked', !$checkbox.is(':checked'));
                $checkbox.triggerHandler('change');
                updateDisplay();
            });

            $checkbox.on('change', function () {
                updateDisplay();
            });

            function updateDisplay() {
                var isChecked = $checkbox.is(':checked');
                // Set the button's state
                $button.data('state', (isChecked) ? "on" : "off");

                // Set the button's icon
                $button.find('.state-icon')
                    .removeClass()
                    .addClass('state-icon ' + settings[$button.data('state')].icon);

                // Update the button's color
                if (isChecked) {
                    $button
                        .removeClass('btn-default')
                        .addClass('btn-' + color + ' active');
                }
                else {
                    $button
                        .removeClass('btn-' + color + ' active')
                        .addClass('btn-default');
                }
            }

            function init() {
                updateDisplay();
                // Inject the icon if applicable
                if ($button.find('.state-icon').length == 0) {
                    $button.prepend('<i class="state-icon ' + settings[$button.data('state')].icon + '"></i> ');
                }
            }
            init();
        });
    });

    $(function () {
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img_prev').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#avatar-upload").change(function () {
            $('#img_prev').removeClass('hidden');
            readURL(this);
        });
    });

    $(document).ready(function () {
        $('.filterable .btn-filter').click(function () {
            var $panel = $(this).parents('.filterable'),
                $filters = $panel.find('.filters input'),
                $tbody = $panel.find('.table tbody');
            if ($filters.prop('disabled') == true) {
                $filters.prop('disabled', false);
                $filters.first().focus();
            } else {
                $filters.val('').prop('disabled', true);
                $tbody.find('.no-result').remove();
                $tbody.find('tr').show();
            }
        });

        $('.filterable .filters input').keyup(function (e) {
            /* Ignore tab key */
            var code = e.keyCode || e.which;
            if (code == '9') return;
            /* Useful DOM data and selectors */
            var $input = $(this),
                inputContent = $input.val().toLowerCase(),
                $panel = $input.parents('.filterable'),
                column = $panel.find('.filters th').index($input.parents('th')),
                $table = $panel.find('.table'),
                $rows = $table.find('tbody tr');
            /* Dirtiest filter function ever ;) */
            var $filteredRows = $rows.filter(function () {
                var value = $(this).find('td').eq(column).text().toLowerCase();
                return value.indexOf(inputContent) === -1;
            });
            /* Clean previous no-result if exist */
            $table.find('tbody .no-result').remove();
            /* Show all rows, hide filtered ones (never do that outside of a demo ! xD) */
            $rows.show();
            $filteredRows.hide();
            /* Prepend no-result row if all rows are filtered */
            if ($filteredRows.length === $rows.length) {
                $table.find('tbody').prepend($('<tr class="no-result text-center"><td colspan="' + $table.find('.filters th').length + '">No result found</td></tr>'));
            }
        });
    });
</script>

Simple_Profiler/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<![endif]-->

Simple_Profiler/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<div id="wrapper">
  <%= render 'layouts/header' %>
  <div id="page-content-wrapper">
    <%= render 'layouts/hamburger' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </div>
</div>
</body>
</html>
<%= render 'layouts/scripts' %>