ADVWEB4-master/advweb/config/routes.rb
Rails.application.routes.draw do
  resources :reports
  devise_scope :user do
    get '/sign_up' => 'devise/registrations#new'
    post '/sign_up' => 'devise/registrations#create'
  end
  devise_for :users
  authenticated :user do
    root 'pages#home'
    get 'pages/list', to: 'pages#list_of_accounts', as: 'list'
    get 'pages/:id/show', to: 'pages#show', as: 'show_account'
    get 'pages/:id/update', to: 'pages#admin', as: 'make_admin'
    get 'pages/:id/approved', to: 'pages#approved', as: 'approved_user'
    delete 'pages/:id/destroy', to: 'pages#destroy', as: 'admin_destroy'
    get 'reports/new', to: 'reports#new'
    post 'reports/new', to: 'reports#create'
    post 'reports/:id/edit', to: 'reports#edit'
    patch 'reports/:id/edit', to: 'reports#update'
    delete 'pictures', to: 'reports#destroy_picture'
  end
  get '/user_profile', to: 'pages#user_profile'
  devise_scope :user do
    root 'devise/sessions#new'
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ADVWEB4-master/advweb/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ADVWEB4-master/advweb/app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :report
end

ADVWEB4-master/advweb/app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true
  validates_presence_of :report_date, :report_description, :report_location, :report_title
end

ADVWEB4-master/advweb/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  has_many :reports, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, authentication_keys: [:login]

  VALID_NAME_REGEX = /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/
  validates :age, presence: true, numericality: { only_integer: true }
  validates :age, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }
  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validates_format_of :first_name, :with => VALID_NAME_REGEX
  validates_format_of :last_name, :with => VALID_NAME_REGEX
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_username
  validates :email, presence: true, length: { maximum: 255 },
            format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create },
            uniqueness: true


  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super # Use whatever other message
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

ADVWEB4-master/advweb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :age, :username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

ADVWEB4-master/advweb/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @reports = Report.all.paginate(page: params[:page], per_page: 5)
  end

  def user_profile
    @user = current_user.reports.paginate(page: params[:page], per_page: 5)
  end

  def list_of_accounts
    if params[:approved] == 'false'
      @user = User.where(approved: false).paginate(page: params[:page], per_page: 5)
    else
      @user = User.all.paginate(page: params[:page], per_page: 5)
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    if @user.destroy
      redirect_to list_path
    end
  end

  def admin
    @user = User.find(params[:id])
    if @user.update_attribute(:is_admin, true)
      flash[:success] = 'Change Successfully'
      redirect_to list_path
    end
  end

  def approved
    @user = User.find(params[:id])
    if @user.update_attribute(:approved, true)
      flash[:success] = 'User Approved'
      redirect_to list_path
    end
  end
end

ADVWEB4-master/advweb/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  def show
    @reports = Report.find(params[:id])
    @pictures = @reports.photos
  end

  def new
    @reports = current_user.reports.build
    @reports.photos.build
  end

  def create
    @reports = current_user.reports.build(report_params)
    if @reports.save
      params[:photos]['picture'].each do |a|
        @reports_picture = @reports.photos.create!(:picture => a, :report_id => @reports.id)
      end
      flash[:success] = 'Report Created'
      redirect_to root_url
    else
      @reports.photos.build
      render 'new'
    end
  end

  def edit
    @reports = Report.find(params[:id])
    @reports_picture = @reports.photos
  end

  def update
    @reports = Report.find(params[:id])
    if @reports.update_attributes(report_params)
      flash[:success] = 'Report Created'
      redirect_to report_path(@reports)
    else
      render 'edit'
    end
  end

  def destroy
    Report.find(params[:id]).destroy
    flash[:success] = "Report deleted"
    redirect_to root_path
  end

  def destroy_picture
    Photo.find(params[:id]).remove_picture!
    redirect_to root_path
  end

  private

  def report_params
    params.require(:report).permit(:report_title, :report_date,
                                   :report_location, :report_description,
                                   photos_attributes: [:id, :report_id, :picture])
  end
end

ADVWEB4-master/advweb/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = ' ')
    base_title = "Website Name"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

ADVWEB4-master/advweb/app/helpers/pages_helper.rb
module PagesHelper
end

ADVWEB4-master/advweb/app/helpers/reports_helper.rb
module ReportsHelper
end

ADVWEB4-master/advweb/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    My website
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

ADVWEB4-master/advweb/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

ADVWEB4-master/advweb/app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

ADVWEB4-master/advweb/app/views/layouts/_script.html.erb
<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });

    $(document).ready(function() {
        $('#found_site').on('change', function() {
            $(this).val() == "other" ? $('#specify').closest('.form-group').show() : $('#specify').closest('.form-group').hide();
        })
    })

    $(function () {
        $('#datetimepicker1').datetimepicker({
            format:'DD/MM/YYYY HH:mm',
        });
    });
</script>

ADVWEB4-master/advweb/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

ADVWEB4-master/advweb/app/views/layouts/_side_menu.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand">
      <%= link_to 'Very Awesome Reporting',   root_path %>
    </li>
    <li>
      <%= link_to 'Create a Report',   reports_new_path %>
    </li>
    <li>
      <%= link_to "#{current_user.username} Reports",   user_profile_path %>
    </li>
    <li>
      <%= link_to 'Settings',   edit_user_registration_path %>
    </li>
    <li>
      <%= link_to 'Logout',   destroy_user_session_path, method: :delete %>
    </li>
    <% if current_user.is_admin? %>
      <li>
        <%= link_to 'List of Accounts',   list_path %>
      </li>
    <% end %>
  </ul>
</div>

ADVWEB4-master/advweb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <% if user_signed_in? %>
  <div id="wrapper">
    <%= render 'layouts/side_menu' %>
    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
    <body style="background-image: url('http://img.jakpost.net/c/2017/10/16/2017_10_16_34091_1508126152._large.jpg');
    background-attachment: fixed">
      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <%= render 'layouts/messages' %>
              <%= yield %>
              <%= render 'layouts/footer' %>
            </div>
          </div>
        </div>
      </div>
      </body>
  <% else %>
<body style="background-image: url('http://img.jakpost.net/c/2017/10/16/2017_10_16_34091_1508126152._large.jpg');
    background-attachment: fixed">
  <%= yield %>
</body>
  <% end %>
    </div>
</html>
<%= render 'layouts/script' %>

ADVWEB4-master/advweb/app/views/pages/home.html.erb
<% provide(:title, "Home")%>
<div class="jumbotron" style="background: rgba(245,245,245,0.7)">
  <h4 class="center" style="color:#272287; text-align: center"> R E P O R T S (<%= @reports.count %>)</h4>
  <% if @reports.any? %>
    <% @reports.each do |reports|%>
      <div id = "report-link">
        <%= link_to report_path(reports) do %>
          <h3><%= reports.report_title %></h3>
          <small><%= reports.report_date %></small>
          <%= reports.report_description%> <br><br>
        <% end %>
      </div>
    <% end %>
    <%= will_paginate @reports %>
<% else %>
  <% end %>
</div>

ADVWEB4-master/advweb/app/views/pages/list_of_accounts.html.erb
<% provide(:title, "Accounts")%>
<div class="jumbotron" style="background: rgba(245,245,245,0.7)">
  <h4 class="center" style="color:#272287; text-align: center"> List of User's Account </h4>
  <h2>Accounts (<%= @user.count %>)</h2>
  <% if @user.any? %>
  <table class="table table-hover">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Approved</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @user.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td>
        <% if user.approved? %>
          Yes
        <% else %>
          No
        <% end %>
      </td>
      <td>
        <% if current_user != user %>
          <%= link_to 'Destroy', admin_destroy_path(user), method: :delete, data: { confirm: "You sure?" } %>
          <% unless user.is_admin? %>
            | <%= link_to 'Admin', make_admin_path(user)%>
          <% end %>
          <% unless user.approved? %>
            | <%= link_to 'Approve', approved_user_path(user)%>
          <% end %>
        <% end %>
      </td>
    </tr>
    <% end %>
    <%= will_paginate @user %>
  <% end %>
    </tbody>
  </table>

</div>

ADVWEB4-master/advweb/app/views/pages/show.html.erb
<div class="jumbotron" style="background: rgba(245,245,245,0.7)">
  <%= @user.id %><br>
  <%= @user.first_name %> <%= @user.last_name %><br>
  <%= @user.username %><br>
  <%= @user.email %>
</div>

ADVWEB4-master/advweb/app/views/pages/user_profile.html.erb
<% provide(:title, "User Reports")%>
<div class="jumbotron" style="background: rgba(245,245,245,0.7)">
  <h4 class="center" style="color:#272287; text-align: center">R E P O R T S (<%= @user.count %>)</h4>
  <% if @user.any? %>
    <% @user.each do |reports|%>
      <div id = "report-link">
        <%= link_to report_path(reports) do %>
          <h3><%= reports.report_title %></h3>
          <small><%= reports.report_date %></small>
          <%= reports.report_description%> <br><br>
        <% end %>
      </div>
    <% end %>
    <%= will_paginate @user %>
  <% else %>
  <% end %>
</div>

ADVWEB4-master/advweb/app/views/reports/edit.html.erb
<% provide(:title, "Edit Report") %>
<div class="container">
  <div class="row">

    <div class="col-md-8 col-md-offset-2">
      <%= form_for @reports, url: edit_report_path(@reports), html: { multipart: true }  do |f| %>
        <%= render 'reports/shared/error_messages' %>
        <legend class="text-center">Edit Report details</legend>
        <fieldset>
          <legend>Report Details</legend>

          <div class="form-group col-md-6">
            <%= f.label :'Title' %>
            <%= f.text_field :report_title, class: 'form-control', :placeholder => 'Title of your Report', id: 'report_title' %>
          </div>

          <div class="form-group col-md-6">
            <%= f.label :'Date' %>
            <div class='input-group date' id='datetimepicker1'>
              <%= f.text_field :report_date, class: 'form-control', class: 'form-control' %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>

          <div class="form-group col-md-12">
            <%= f.label :'Address' %>
            <%= f.text_field :report_location, class: 'form-control', :placeholder => 'Address of the scene' %>
          </div>

          <div class="form-group col-md-12">
            <%= f.label :'Description' %>
            <%= f.text_area :report_description, class: 'form-control', :placeholder => 'Description of the scene...' %>
          </div>

        </fieldset>
        <div class="form-group">
          <div class="col-md-12">
            <%= f.submit 'Submit Report', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

ADVWEB4-master/advweb/app/views/reports/new.html.erb
<% provide(:title, "Report a Scene")%>
<div class="jumbotron" style="background: rgba(245,245,245,0.7)">
  <div class="row">

    <div class="col-md-8 col-md-offset-2">
      <%= form_for @reports, url: reports_new_path do |f| %>
        <%= render 'reports/shared/error_messages' %>
        <%= render :partial => 'reports/shared/fields', :locals => { :f => f } %>
      <% end %>
    </div>
  </div>
</div>

ADVWEB4-master/advweb/app/views/reports/shared/_error_messages.html.erb
<% if @reports.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@reports.errors.count, 'error') %>.
    </div>
    <ul>
      <% @reports.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

ADVWEB4-master/advweb/app/views/reports/shared/_fields.html.erb
<legend class="text-center"><h3 style="color:#272287">R E P O R T &nbsp; A &nbsp; S C E N E</h3></legend>
<fieldset>
  <legend><h4 style="color:#808080; text-align: center">R e p o r t &nbsp; D e t a i l s</h4></legend>

  <div class="form-group col-md-6">
    <%= f.label :'Title' %>
    <%= f.text_field :report_title, class: 'form-control', :placeholder => 'Title of your Report', id: 'report_title' %>
  </div>

  <div class="form-group col-md-6">
    <%= f.label :'Date' %>
    <div class='input-group date' id = 'datetimepicker1'>
      <%= f.text_field :report_date, class: 'form-control',class: 'form-control form_datetime' %>
      <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
    </div>
  </div>

  <div class="form-group col-md-12">
    <%= f.label :'Location' %>
    <%= f.text_field :report_location, class: 'form-control', :placeholder => 'Location' %>
  </div>

  <div class="form-group col-md-12">
    <%= f.label :'Description' %>
    <%= f.text_area :report_description, class: 'form-control', :placeholder => 'Description' %>
  </div>

</fieldset>

<fieldset>
  <legend>Pictures</legend>
  <div class="form-group col-md-6">
    <%= f.fields_for :photos do |p| %>
      <div class="field">
        <%= p.file_field :picture, class: 'form-control', :multiple => true, name: "photos[picture][]" %>
      </div>
    <% end %>
  </div>
</fieldset>

<div class="form-group">
  <div class="col-md-12">
    <%= f.submit 'Submit Report', class: 'btn btn-primary' %>
  </div>
</div>

ADVWEB4-master/advweb/app/views/reports/show.html.erb
<% provide(:title, "Report")%>
<h1 class = "center">Reports#show</h1>
<div class="jumbotron">
  <h3><%= @reports.report_title %></h3>
  <small><%= @reports.report_date %></small><br>
  <small>created by <%= @reports.user.username %></small><br>
  <%= @reports.report_description%> <br><br>
  <% @pictures.each do |pictures| %>
      <div class="gallery">
        <%= link_to pictures.picture.url do %>
          <%= image_tag pictures.picture.url(:report_picture) if pictures.picture? %>
        <% end %>
      </div>
  <% end %>

  <div class="clearfix"></div>
  <br>

  <%= link_to 'Back', root_path %> |

  <% if current_user.id == @reports.user.id %>
    <%= link_to 'Edit', edit_report_path(@reports) %> |
  <% end %>

  <% if current_user.is_admin? %>
    <%= link_to 'Delete', @reports, method: :delete,
                  data: {confirm: "You sure?"} %>
  <% end %>
</div>

ADVWEB4-master/advweb/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>