Simple_Profiler/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root 'profiles#user_page'
    get 'main/list_of_users', to: 'main#list_of_users', as: 'accounts'
    get 'main/:id/admin', to: 'main#admin', as: 'make_admin'
    get 'main/:id/approved', to: 'main#approved', as: 'approved'
    resources :profiles, :only => [:index, :show, :edit, :new]
      patch 'profiles/:id/edit', to: 'profiles#update'
      post 'profiles/new', to: 'profiles#create'
    resources :trainings, :only => [:index, :show, :edit, :destroy, :new]
      patch 'trainings/:id/edit', to: 'trainings#update'
      post 'trainings/new', to: 'trainings#create'
    resources :accomplishments, :only => [:index, :show, :edit, :destroy, :new]
      patch 'accomplishments/:id/edit', to: 'accomplishments#update'
      post 'accomplishments/new', to: 'accomplishments#create'
  end
  root 'main#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Simple_Profiler/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :training, :dependent => :destroy
  has_many :accomplishment, :dependent => :destroy
  mount_uploader :profile_picture, PhotoUploader
  validates_presence_of :date_of_birth, :education, :contact_number, :gender, :civil_status
end

Simple_Profiler/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  def index
    @profile = Profile.all
  end

  def show
    @datetime = DateTime.now
    @user = User.find(params[:id])
    @profile = @user.profile
    @training = @profile.training.paginate(:page => params[:page], :per_page => 5)
    @accomplishment = @profile.accomplishment.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @profile = current_user.build_profile
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "You successfully created a profile!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile updated"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def user_page
    @user = current_user
    if !@user.profile.nil?
      @datetime = DateTime.now
      @profile = @user.profile
      @training = @profile.training.paginate(:page => params[:page], :per_page => 5)
      @accomplishment = @profile.accomplishment.paginate(:page => params[:page], :per_page => 15)
    else
      redirect_to new_profile_path
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:profile_picture, :remove_profile_picture, :date_of_birth,
                                    :civil_status, :gender, :contact_number,
                                    :education, :biography, :location_city, :main_skill,
                                    :main_hobby, :education_status, :interest)
  end
end

Simple_Profiler/app/helpers/profiles_helper.rb
module ProfilesHelper
end

Simple_Profiler/app/views/profiles/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Profiles#edit</h1>
<div class=" row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @profile, url: edit_profile_path(current_user.profile) do |f| %>
      <%= render 'profiles/shared/error_messages' %>
      <%= render :partial => 'profiles/shared/fields', :locals => { :f => f } %>
      <div class="row">
        <div class="col-xs-12 col-md-6"><%= f.submit 'Submit', class: 'btn btn-primary' %></div>
      </div>
    <% end %>
  </div>
</div>

Simple_Profiler/app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

Simple_Profiler/app/views/profiles/new.html.erb
<% provide(:title, "Profile") %>
<h1>Profiles#new</h1>
<div class=" row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @profile, url: new_profile_path, html: { multipart: true } do |f| %>
      <%= render 'profiles/shared/error_messages' %>
      <%= render :partial => 'profiles/shared/fields', :locals => { :f => f } %>
      <div class="row">
        <div class="col-xs-12 col-md-6"><%= f.submit 'Submit', class: 'btn btn-primary' %></div>
      </div>
    <% end %>
  </div>
</div>

Simple_Profiler/app/views/profiles/show.html.erb
<% provide(:title, "Home") %>

<div class="container">
  <div class="toppad  pull-right ">
    <br>
    <%= link_to 'Back', 'javascript:history.back()' %> |
    <%= link_to 'Go to profile', current_user_page_path %>
    <br>
    <p class=" text-info"><%= @datetime.strftime('%-d/%-m/%y: %I:%M %p') %> </p>
  </div>
  <h1>User ID: <%= @user.id %></h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <div id="user-profile-2" class="user-profile">
        <div class="tabbable">
          <ul class="nav nav-tabs padding-18">
            <li class="active">
              <a data-toggle="tab" href="#home">
                <i class="green ace-icon fa fa-user bigger-120"></i>
                Profile
              </a>
            </li>

            <li>
              <a data-toggle="tab" href="#training">
                <i class="orange ace-icon fa fa-rss bigger-120"></i>
                Training
              </a>
            </li>

            <li>
              <a data-toggle="tab" href="#award">
                <i class="pink ace-icon fa fa-picture-o bigger-120"></i>
                Achievements
              </a>
            </li>
          </ul>
          <div class="tab-content no-border padding-24">
            <div id="home" class="tab-pane in active">
              <div class="row">
                <div class="col-xs-12 col-sm-3 center">
      							<span class="profile-picture">
                        <%= image_tag @profile.profile_picture.url(:in_profile), class: 'editable img-responsive',
                                      alt: ' Avatar', id: 'avatar2' %>
      							</span>

                  <div class="space space-4"></div>
                </div>

                <div class="col-xs-12 col-sm-9">
                  <h4 class="blue">
                    <span class="middle"><%= full_name(@user.first_name, @user.last_name) %></span>
                  </h4>

                  <div class="profile-user-info">
                    <div class="profile-info-row">
                      <div class="profile-info-name"> Username</div>
                      <div class="profile-info-value">
                        <span><%= @user.username %></span>
                      </div>
                    </div>

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Date of Birth</div>
                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.date_of_birth %></span>
                      </div>
                    </div>

                    <!--
                    <div class="profile-info-row">
                      <div class="profile-info-name"> Location</div>
                      <div class="profile-info-value">
                        <i class="fa fa-map-marker light-orange bigger-110"></i>
                      </div>
                    </div>
                    -->

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Civil Status</div>
                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.civil_status %></span>
                      </div>
                    </div>

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Gender</div>

                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.gender %></span>
                      </div>
                    </div>

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Contact</div>

                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.contact_number %></span>
                      </div>
                    </div>
                  </div>

                  <div class="hr hr-8 dotted"></div>

                  <div class="profile-user-info">
                    <div class="profile-info-row">
                      <div class="profile-info-name"> College</div>

                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.education %></span>
                      </div>
                    </div>
                  </div>
                </div><!-- /.col -->
              </div><!-- /.row -->

              <div class="space-20"></div>

              <div class="row">
                <div>
                  <div class="widget-box transparent">
                    <div class="widget-header widget-header-small">
                      <h4 class="widget-title smaller">
                        <i class="ace-icon fa fa-check-square-o bigger-110"></i>
                        Biography
                      </h4>
                    </div>

                    <div class="widget-body">
                      <div class="widget-main">
                        <p>
                          <%= @profile.nil? ? ' ' : @profile.biography %>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div><!-- /#home -->

            <!-- /#Training -->
            <div id="training" class="tab-pane">
              <div class="profile-feed row">
                <% @training.each do |training| %>
                  <div class="profile-activity clearfix">
                    <div>
                      <img class="pull-left" alt="Alex Doe's avatar" src="http://bootdey.com/img/Content/avatar/avatar1.png">
                      <%= link_to training.speaker , training_path(training) %><br>
                      <%= training.type_of_training %><br>
                      <div class="time">
                        <i class="ace-icon fa fa-clock-o bigger-110"></i>
                        <%= training.date_of_training %>
                      </div>
                    </div>
                  </div>
                <% end %>
                <%= will_paginate @training %>
              </div>
              <br>
              <div class="space-12"></div>
            </div>

            <!-- /#award -->
            <div id="award" class="tab-pane">
              <div class="space-12"></div>
              <br>
              <% @accomplishment.each do |award| %>
                <ul class="ace-thumbnails">
                  <li>
                    <a href="#" data-rel="colorbox">
                      <img alt="150x150" src="http://lorempixel.com/200/200/nature/1/">
                      <div class="text">
                        <div class="inner"><%= award.title %></div>
                      </div>
                    </a>

                    <div class="tools tools-bottom">
                      <%= link_to accomplishment_path(award) do %>
                        <i class="ace-icon fa fa-link"></i>
                      <% end %>
                    </div>
                  </li>
                </ul>
              <% end %>
            </div>
            </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

Simple_Profiler/app/views/profiles/user_page.html.erb
<% provide(:title, "Home") %>

<div class="container">
  <div class="toppad  pull-right ">
    <br>
    <% if @profile.nil? %>
      <%= link_to 'Create Profile', new_profile_path %> |
    <% else %>
      <%= link_to 'Edit Profile', edit_profile_path(@profile) %> |
    <% end %>
    <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
    <br>
    <p class=" text-info"><%= @datetime.strftime('%-d/%-m/%y: %I:%M %p') %> </p>
  </div>
  <h1>User ID: <%= @user.id %></h1>
  <div class="panel panel-default">
    <div class="panel-body">
      <div id="user-profile-2" class="user-profile">
        <div class="tabbable">
          <ul class="nav nav-tabs padding-18">
            <li class="active">
              <a data-toggle="tab" href="#home">
                <i class="green ace-icon fa fa-user bigger-120"></i>
                Profile
              </a>
            </li>

            <li>
              <a data-toggle="tab" href="#training">
                <i class="orange ace-icon fa fa-rss bigger-120"></i>
                Training
              </a>
            </li>

            <li>
              <a data-toggle="tab" href="#award">
                <i class="pink ace-icon fa fa-picture-o bigger-120"></i>
                Achievements
              </a>
            </li>
          </ul>
          <div class="tab-content no-border padding-24">
            <div id="home" class="tab-pane in active">
              <div class="row">
                <div class="col-xs-12 col-sm-3 center">
      							<span class="profile-picture">
                        <%= image_tag @profile.profile_picture.url(:in_profile), class: 'editable img-responsive',
                                    alt: ' Avatar', id: 'avatar2' %>
      							</span>

                  <div class="space space-4"></div>
                </div>

                <div class="col-xs-12 col-sm-9">
                  <h4 class="blue">
                    <span class="middle"><%= full_name(@user.first_name, @user.last_name) %></span>
                  </h4>

                  <div class="profile-user-info">
                    <div class="profile-info-row">
                      <div class="profile-info-name"> City</div>

                      <div class="profile-info-value">
                        <i class="fa fa-map-marker light-orange bigger-110"></i>
                        <span><%= @profile.nil? ? ' ' : @profile.location_city %></span>
                      </div>
                    </div>

                      <div class="profile-info-row">
                        <div class="profile-info-name"> Date of Birth</div>

                        <div class="profile-info-value">
                          <span><%= @profile.nil? ? ' ' : @profile.date_of_birth %></span>
                        </div>
                      </div>

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Age</div>
                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : age(@profile.date_of_birth) %></span>
                      </div>
                    </div>

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Interest</div>
                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.interest %></span>
                      </div>
                    </div>

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Main Skill</div>
                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.main_skill %></span>
                      </div>
                    </div>

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Main Hobby</div>
                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.main_hobby %></span>
                      </div>
                    </div>


                    <div class="profile-info-row">
                      <div class="profile-info-name"> Civil Status</div>

                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.civil_status %></span>
                      </div>
                    </div>

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Gender</div>
                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.gender %></span>
                      </div>
                    </div>

                    <div class="profile-info-row">
                      <div class="profile-info-name"> Contact</div>
                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.contact_number %></span>
                      </div>
                    </div>
                    <div class="profile-info-row">
                      <div class="profile-info-name">Education</div>

                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.education_status %></span>
                      </div>
                    </div>
                  </div>

                  <div class="profile-user-info">
                    <div class="profile-info-row">
                      <div class="profile-info-name"> School</div>
                      <div class="profile-info-value">
                        <span><%= @profile.nil? ? ' ' : @profile.education %></span>
                      </div>
                    </div>
                  </div>
                </div><!-- /.col -->
              </div><!-- /.row -->

              <div class="hr hr-8 dotted"></div>
              <div class="space-20"></div>

              <div class="row">
                <div>
                  <div class="widget-box transparent">
                    <div class="widget-header widget-header-small">
                      <h4 class="widget-title smaller">
                        <i class="ace-icon fa fa-check-square-o bigger-110"></i>
                        About Me
                      </h4>
                    </div>

                    <div class="widget-body">
                      <div class="widget-main">
                        <p>
                          <%= @profile.nil? ? ' ' : simple_format(@profile.biography) %>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div><!-- /#home -->

            <!-- /#Training -->
            <div id="training" class="tab-pane">
              <div class="profile-feed row">
                    <% @training.each do |training| %>
                      <div class="profile-activity clearfix">
                        <div>
                          <img class="pull-left" alt="Alex Doe's avatar" src="http://bootdey.com/img/Content/avatar/avatar1.png">
                          <%= link_to training.speaker , training_path(training) %><br>
                          <%= training.type_of_training %><br>
                          <div class="time">
                            <i class="ace-icon fa fa-clock-o bigger-110"></i>
                            <%= training.date_of_training %>
                          </div>
                        </div>
                        <div class="tools action-buttons">
                          <%= link_to edit_training_path(training), class: 'red' do %>
                            <i class="ace-icon fa fa-pencil bigger-125"></i>
                          <% end %>
                          <%= link_to training_path(training),
                                      method: :delete, class: 'blue' do %>
                            <i class="ace-icon fa fa-times bigger-125"></i>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  <%= will_paginate @training %>
              </div>
              <br>
              <div class="space-12"></div>
              <div class="center">
                <%= link_to new_training_path, class: 'btn btn-sm btn-primary btn-white btn-round' do %>
                  <span class="bigger-110">Create Training Information </span>
                  <i class="icon-on-right ace-icon fa fa-plus-square"></i>
                <% end %>
              </div>
            </div>

            <!-- /#award -->
            <div id="award" class="tab-pane">
              <div class="space-12"></div>
              <div class="center">
                <%= link_to new_accomplishment_path, class: 'btn btn-sm btn-primary btn-white btn-round' do %>
                  <span class="bigger-110">Create Achievement </span>
                  <i class="icon-on-right ace-icon fa fa-plus-square"></i>
                <% end %>
              </div>
              <br>
                <% @accomplishment.each do |award| %>
                  <ul class="ace-thumbnails">
                    <li>
                      <a href="#" data-rel="colorbox">
                        <img alt="150x150" src="http://lorempixel.com/200/200">
                        <div class="text">
                          <div class="inner"><%= award.title %></div>
                        </div>
                      </a>

                      <div class="tools tools-bottom">
                        <%= link_to accomplishment_path(award) do %>
                          <i class="ace-icon fa fa-link"></i>
                        <% end %>

                        <%= link_to edit_accomplishment_path(award) do %>
                          <i class="ace-icon fa fa-pencil"></i>
                        <% end %>

                        <%= link_to accomplishment_path(award), method: :delete do %>
                          <i class="ace-icon fa fa-times red"></i>
                        <% end %>
                      </div>
                    </li>
                  </ul>
                <% end %>
                  </div>
                </li>
              </ul>
          </div>
        </div>
      </div>
      </div>
    </div>
    </div>
  </div>
</div>